pipeline {

    agent none

    stages {
        // build the docker image
        stage('docker-build') {
            when{
                changeset '**/vote/**'
            }
            agent any
            steps {
                docker.build("mrscrb/vote:v${env.BUILD_ID}", "./vote")
            }
        }
        // TODO run the apps tests
        stage('docker-test') {
            when{
                changeset '**/vote/**'
            }
            agent any
            steps {
                echo '[Placeholder] Running tests'
            }
        }
        stage('docker-package'){
            agent any
            when{
                branch 'master'
                changeset '**/vote/**'
            }
            steps{
                echo 'Pushing dockerized vote app to registry'
                script{
                    docker.withRegistry('https://index.docker.io/v1/','dockerhub-rw') {
                        def voteImage = docker.image("mrscrb/vote:v${env.BUILD_ID}")
                        voteImage.push()
                        voteImage.push("latest")
                    }
                }
            }
        }
    }
    post {
        always {
            echo 'Building multibranch pipeline for vote is completed.'
        }
    }
}
